### ISSUE TITLE
Feat: 상세 내역 관련 api 수정으로 인한 로직 전면 수정

### ISSUE THREAD

**Issue by Jong1co** [so-sim/front#103]
## 💎 개발할 기능

dateFilter 관련 로직 수정

## ✔️ Todo

- **Calendar**
  - [x] calendar 관련 api 업데이트로 인한 로직 수정
  - [x] mock data 생성

- **DetailFine**
  - [x] dateFilter 로직 전체 수정
    - [ ] DateFilter 클래스 -> useD
  - [x] api 업데이트로 인한 로직 수정
  - [x] mock data 생성
 
## 📖 참고 사항

[노션 api 명세](https://www.notion.so/74e9ee26a64b435aa90774c65d8179c6?pvs=4)
